name = "termul-landing"
pages_build_output_dir = "./dist"
compatibility_date = "2026-05-31"

[[d1_databases]]
binding = "DB"
database_name = "termul"
database_id = "ee92f4d8-1498-45dd-acd3-99b1fe25f35b"
preview_database_id = "DB"

[[r2_buckets]]
binding = "TESTIMONIAL_AVATARS"
bucket_name = "termul"
